# See schema in factory_schema_config_task.py for descriptions of common parameters.

defaults:
    - _self_
    # - /factory_schema_config_task

name: FactoryTaskNutBoltPick
physics_engine: ${..physics_engine}

sim:
  use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
  dt: 0.00833333333 #0.016667  # required, but overridden in FactoryBase.yaml
  gravity: [0.0, 0.0, -9.81]  # required, but overridden in base FactoryBase.yaml
  disable_gravity: False
  add_ground_plane: True
  add_distant_light: True
  use_flatcache: True
  enable_scene_query_support: True
  disable_contact_processing: False

  default_material:
    static_friction: 1.0
    dynamic_friction: 1.0
    restitution: 0.0
  
  physx:
    # per-scene
    use_gpu: ${eq:${....sim_device},"gpu"} # set to False to run on CPU
    solver_position_iteration_count: 16
    solver_velocity_iteration_count: 0
    contact_offset: 0.005
    rest_offset: 0.0
    worker_thread_count: ${....num_threads}
    solver_type: ${....solver_type} # 0: PGS, 1: TGS
    bounce_threshold_velocity: 0.2
    friction_offset_threshold: 0.01
    friction_correlation_distance: 0.00625
    max_depenetration_velocity: 5.0
    enable_sleeping: True
    enable_stabilization: True

    # GPU buffers
    gpu_max_rigid_contact_count: 524288
    gpu_max_rigid_patch_count: 33554432
    gpu_found_lost_pairs_capacity: 10379
    gpu_found_lost_aggregate_pairs_capacity: 262144 
    gpu_total_aggregate_pairs_capacity: 1048576
    gpu_max_soft_body_contacts: 1048576
    gpu_max_particle_contacts: 1048576
    gpu_heap_capacity: 33554432
    gpu_temp_buffer_capacity: 16777216
    gpu_max_num_partitions: 8

  franka:
    # -1 to use default values
    override_usd_defaults: False
    enable_self_collisions: True
    enable_gyroscopic_forces: True
    # also in stage params
    # # per-actor
    solver_position_iteration_count: 16
    solver_velocity_iteration_count: 0
    sleep_threshold: 0.005
    stabilization_threshold: 0.001
    # per-body
    density: -1
    max_depenetration_velocity: 5.0
    # per-shape
    contact_offset: 0.005
    rest_offset: 0.0
  

env:
  controlFrequencyInv: 2 # 60 hz
  numEnvs: ${resolve_default:128,${...num_envs}}
  numObservations: 20
  numActions: 12

  close_and_lift: True  # close gripper and lift after last step of episode
  num_gripper_move_sim_steps: 40 #20  # number of timesteps to reserve for moving gripper before first step of episode
  num_gripper_close_sim_steps: 50 #25  # number of timesteps to reserve for closing gripper after last step of episode
  num_gripper_lift_sim_steps: 50 #25  # number of timesteps to reserve for lift after last step of episode

randomize:
  franka_arm_initial_dof_pos: [0.3413, -0.8011, -0.0670, -1.8299,  0.0266,  1.0185,  1.0927]
  fingertip_midpoint_pos_initial: [0.0, -0.2, 0.2]  # initial position of hand above table
  fingertip_midpoint_pos_noise: [0.2, 0.2, 0.1]  # noise on hand position
  fingertip_midpoint_rot_initial: [3.1416, 0, 3.1416]  # initial rotation of fingertips (Euler)
  fingertip_midpoint_rot_noise: [0.3, 0.3, 1]  # noise on rotation
  nut_pos_xy_initial: [0.0, -0.3]  # initial XY position of nut on table
  nut_pos_xy_initial_noise: [0.1, 0.1]  # noise on nut position
  bolt_pos_xy_initial: [0.0, 0.0]  # initial position of bolt on table
  bolt_pos_xy_noise: [0.1, 0.1]  # noise on bolt position

rl:
  pos_action_scale: [0.1, 0.1, 0.1]
  rot_action_scale: [0.1, 0.1, 0.1]
  force_action_scale: [1.0, 1.0, 1.0]
  torque_action_scale: [1.0, 1.0, 1.0]

  clamp_rot: True
  clamp_rot_thresh: 1.0e-6

  num_keypoints: 4  # number of keypoints used in reward
  keypoint_scale: 0.5  # length of line of keypoints

  keypoint_reward_scale: 1.0  # scale on keypoint-based reward
  action_penalty_scale: 0.0  # scale on action penalty

  max_episode_length: 100 # 200

  success_bonus: 0.0  # bonus if nut has been lifted

ctrl:
  ctrl_type: joint_space_id  # {gym_default,
                              #  joint_space_ik, joint_space_id, 
                              #  task_space_impedance, operational_space_motion, 
                              #  open_loop_force, closed_loop_force,
                              #  hybrid_force_motion}
  all:
    jacobian_type: geometric
    gripper_prop_gains: [50, 50]
    gripper_deriv_gains: [2, 2]
  gym_default:
    ik_method: dls
    joint_prop_gains: [40, 40, 40, 40, 40, 40, 40]
    joint_deriv_gains: [8, 8, 8, 8, 8, 8, 8]
    gripper_prop_gains: [500, 500]
    gripper_deriv_gains: [20, 20]
  joint_space_ik:
    ik_method: dls
    joint_prop_gains: [1, 1, 1, 1, 1, 1, 1]
    joint_deriv_gains: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
  joint_space_id:
    ik_method: dls
    joint_prop_gains: [40, 40, 40, 40, 40, 40, 40]
    joint_deriv_gains: [8, 8, 8, 8, 8, 8, 8]
  task_space_impedance:
    motion_ctrl_axes: [1, 1, 1, 1, 1, 1]
    task_prop_gains: [40, 40, 40, 40, 40, 40]
    task_deriv_gains: [8, 8, 8, 8, 8, 8]
  operational_space_motion:
    motion_ctrl_axes: [1, 1, 1, 1, 1, 1]
    task_prop_gains: [1, 1, 1, 1, 1, 1]
    task_deriv_gains: [1, 1, 1, 1, 1, 1]
  open_loop_force:
    force_ctrl_axes: [0, 0, 1, 0, 0, 0]
  closed_loop_force:
    force_ctrl_axes: [0, 0, 1, 0, 0, 0]
    wrench_prop_gains: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
  hybrid_force_motion:
    motion_ctrl_axes: [1, 1, 0, 1, 1, 1]
    task_prop_gains: [40, 40, 40, 40, 40, 40]
    task_deriv_gains: [8, 8, 8, 8, 8, 8]
    force_ctrl_axes: [0, 0, 1, 0, 0, 0]
    wrench_prop_gains: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
