# used to create the object
name: HumanoidViewMotion

physics_engine: ${..physics_engine}

# if given, will override the device setting in gym.
env:
  numEnvs: ${resolve_default:4096,${...num_envs}}
  envSpacing: 5
  episodeLength: 300
  cameraFollow: False # if the camera follows humanoid or not
  isFlagrun: False
  enableDebugVis: False

  pdControl: True
  powerScale: 1.0
  controlFrequencyInv: 2 # 30 Hz
  stateInit: "Random"
  hybridInitProb: 0.5
  numAMPObsSteps: 10

  localRootObs: False
  keyBodies: ["right_hand", "left_hand", "right_foot", "left_foot"]
  contactBodies: ["right_foot", "left_foot"]
  terminationHeight: 0.15
  enableEarlyTermination: True

  # animation files to learn from
  motion_file: None

  asset:
    assetFileName: "mjcf/amp_humanoid.xml"
    assetBodyNum: 15
    assetJointNum: 28

  plane:
    staticFriction: 1.0
    dynamicFriction: 1.0
    restitution: 0.0

sim:
  dt: 0.0166 # 1/60 s
  substeps: 2
  up_axis: "z"
  use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
  gravity: [ 0.0, 0.0, -9.81 ]
  physx:
    num_threads: 4
    solver_type: 1  # 0: pgs, 1: tgs
    num_position_iterations: 4
    num_velocity_iterations: 0
    contact_offset: 0.02
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 10.0
    default_buffer_size_multiplier: 10.0

  flex:
    num_inner_iterations: 10
    warm_start: 0.25

task:
  randomize: False