name: LiftObject
experiment_name: ${resolve_default:LiftObject,${..experiment}}
physics_engine: ${..physics_engine}
rl_device: ${..rl_device}

task:
  # List of objects to be included in the task.
  ycbObjects: [ "014_lemon" ]
  egadObjects: [ ]
  # List of measures/states to be returned as the observation.
  observationType: [ "handPose","handDofPos", "objectPos", "objectRot" ]
  # Dimensionality of said measures
  num_observations:
    fingertipContactForces: 15
    fingertipPos: 15
    handDofPos: 5
    handPose: 7
    jointPos: 17
    jointVel: 17
    objectBboxBounds: 6
    objectBboxCorners: 24
    objectBboxPose: 7
    objectSurfaceSamples: 60
    objectPos: 3
    objectLinVel: 3
    objectRot: 4
    objectAngVel: 3
    previousAction: 11
  returnObsDict: False    

debug:
  verbose: True
  visualization: False
  drawEefPose: False
  drawTrackerPose: False
  drawFingertipPose: False
  drawObjectPose: False
  drawObjectBbox: False
  drawObjectSurfaceSamples: False
  drawHandObjectDistance: False
  drawObjectTargetDistance: False
  drawFingertipContactForces: False
  colorObjectsOnSuccess: False
  colorFingertipContactForce: False

#cameras:
#  save_recordings: ${...save_recordings}
#  convert_to_pointcloud: True
#  convert_to_voxelgrid: True
#  camera0:
#    type: rgbd
#    pos: [ 0.0, -0.5, 1.3 ]
#    lookat: [ 0,  0, 0.8 ]
#    horizontal_fov: 70
#    width: 128
#    height: 128
#  camera1:
#    type: rgbd
#    pos: [ 0.0, 0.5, 1.3 ]
#    lookat: [ 0,  0, 0.8 ]
#    horizontal_fov: 70
#    width: 128
#    height: 128

initState:
  noise:
    objectPos: 0.05
    robotDofPos: 0.01

asset:
  robotAssetFile: "urdf/sih/ur5e_schunk_sih_right.urdf"
  tableAssetFile: "urdf/table/table.urdf"
  ycbObjectAssetRoot: "urdf/ycb"
  egadObjectAssetRoot: "urdf/egad/train"
  robotProps:
    armStiffness: 1e4
    armDamping: 300
    handStiffness: 10
    handDamping: 0.5

reward:
  scale:
    actionPenalty: 0.0 #-0.002
    fingertipsToObjectDistanceReward: 1.0
    objectHeightReward: 0.5
    objectVelocityReward: 0.0
    targetHeightReward: 5000.0
    objectFallsOffTablePenalty: -500.0
  liftOffHeight: 0.1
  maxXyDrift: 0.2
  targetHeight: 0.2
  epsHeight: 0.02
  epsFingertips: 1.0
  xyCenter: [0., 0.]
  sparse: False
  returnRewardsDict: False

reset:
  maxEpisodeLength: 300
  objectFallsOffTable: True
  objectLifted: True

defaults:
  - control: default
  - domainRandomization: default
  - env: parallel
  - haptics: default
  - sim: default
  - viewer: first_person
