version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

python:
  install:
    - requirements: requirements.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: doc/conf.py