name: Humanoid

physics_engine: 'physx'  #  'physx' or 'flex'
graphics_device_id: 0
sim_device: 'cuda:0'

env:
  numEnvs: 1
  envSpacing: 3.

  asset:
    robot_name: "Humanoid"
    assetRoot:
    assetFile: "mjcf/amp_humanoid.xml"
    init_pose: [0.0, 1.8, 0.0, 0.0, 0.0, 0.0, 1]
    fix_base_link: False
    flip_visual_attachments: False
    armature: 0.01

  object_asset:

sim:
  dt: 0.0166 # 1/60
  substeps: 1
  up_axis: "Z"
  use_gpu_pipeline: False
  gravity: ${if:${eq:${.up_axis}, "Y"}, [0, -9.81, 0], [0, 0, -9.81]}
  physx:
    num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
    solver_type: 1 # 0: pgs, 1: tgs
    use_gpu: False # set to False to run on CPU
    num_position_iterations: 12
    num_velocity_iterations: 1
    contact_offset: 0.005
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 1000.0
    num_subscenes: 4 # Splits the simulation into N physics scenes and runs each one in a separate thread
    contact_collection: 0 # 0: CC_NEVER (don't collect contact info), 1: CC_LAST_SUBSTEP (collect only contacts on last substep), 2: CC_ALL_SUBSTEPS (default - all contacts)
    friction_offset_threshold: 0.001
    friction_correlation_distance: 0.0005