Model_type:
  hotu_humanoid:  # mjcf/hotu_humanoid.xml rb: 15, dof: 34
    name:
      "hotu_humanoid"
    rigid_bodies:
      pelvis: 0
      torso: 1
      head: 2
      right_upper_arm: 3
      right_lower_arm: 4
      right_hand: 5
      left_upper_arm: 6
      left_lower_arm: 7
      left_hand: 8
      right_thigh: 9
      right_shin: 10
      right_foot: 11
      left_thigh: 12
      left_shin: 13
      left_foot: 14
    dofs:
      abdomen_x: 0
      abdomen_y: 1
      abdomen_z: 2
      neck_x: 3
      neck_y: 4
      neck_z: 5
      right_shoulder_x: 6
      right_shoulder_y: 7
      right_shoulder_z: 8
      right_elbow: 9
      right_hand_x: 10
      right_hand_y: 11
      right_hand_z: 12
      left_shoulder_x: 13
      left_shoulder_y: 14
      left_shoulder_z: 15
      left_elbow: 16
      left_hand_x: 17
      left_hand_y: 18
      left_hand_z: 19
      right_hip_x: 20
      right_hip_y: 21
      right_hip_z: 22
      right_knee: 23
      right_ankle_x: 24
      right_ankle_y: 25
      right_ankle_z: 26
      left_hip_x: 27
      left_hip_y: 28
      left_hip_z: 29
      left_knee: 30
      left_ankle_x: 31
      left_ankle_y: 32
      left_ankle_z: 33
    dof_offsets: [0, 3, 6, 9, 10, 13, 16, 17, 20, 23, 24, 27, 30, 31, 34]

  hotu_humanoid_w_qbhand_full:
    name:
      "hotu_humanoid_w_qbhand_full"
    rigid_bodies:
      pelvis: 0
      torso: 1
      head: 2
      right_upper_arm: 3
      right_lower_arm: 4
      right_hand: 5
      # right_qbhand_root_link: 6
      right_qbhand_thumb_knuckle_link: 7
      right_qbhand_thumb_proximal_virtual_link: 8
      right_qbhand_thumb_proximal_link: 9
      right_qbhand_thumb_distal_virtual_link: 10
      right_qbhand_thumb_distal_link: 11
      right_qbhand_index_knuckle_link: 12
      right_qbhand_index_proximal_virtual_link: 13
      right_qbhand_index_proximal_link: 14
      right_qbhand_index_middle_virtual_link: 15
      right_qbhand_index_middle_link: 16
      right_qbhand_index_distal_virtual_link: 17
      right_qbhand_index_distal_link: 18
      right_qbhand_middle_knuckle_link: 19
      right_qbhand_middle_proximal_virtual_link: 20
      right_qbhand_middle_proximal_link: 21
      right_qbhand_middle_middle_virtual_link: 22
      right_qbhand_middle_middle_link: 23
      right_qbhand_middle_distal_virtual_link: 24
      right_qbhand_middle_distal_link: 25
      right_qbhand_ring_knuckle_link: 26
      right_qbhand_ring_proximal_virtual_link: 27
      right_qbhand_ring_proximal_link: 28
      right_qbhand_ring_middle_virtual_link: 29
      right_qbhand_ring_middle_link: 30
      right_qbhand_ring_distal_virtual_link: 31
      right_qbhand_ring_distal_link: 32
      right_qbhand_little_knuckle_link: 33
      right_qbhand_little_proximal_virtual_link: 34
      right_qbhand_little_proximal_link: 35
      right_qbhand_little_middle_virtual_link: 36
      right_qbhand_little_middle_link: 37
      right_qbhand_little_distal_virtual_link: 38
      right_qbhand_little_distal_link: 39
      left_upper_arm: 40
      left_lower_arm: 41
      left_hand: 42
      # left_qbhand_root_link: 43
      left_qbhand_thumb_knuckle_link: 44
      left_qbhand_thumb_proximal_virtual_link: 45
      left_qbhand_thumb_proximal_link: 46
      left_qbhand_thumb_distal_virtual_link: 47
      left_qbhand_thumb_distal_link: 48
      left_qbhand_index_knuckle_link: 49
      left_qbhand_index_proximal_virtual_link: 50
      left_qbhand_index_proximal_link: 51
      left_qbhand_index_middle_virtual_link: 52
      left_qbhand_index_middle_link: 53
      left_qbhand_index_distal_virtual_link: 54
      left_qbhand_index_distal_link: 55
      left_qbhand_middle_knuckle_link: 56
      left_qbhand_middle_proximal_virtual_link: 57
      left_qbhand_middle_proximal_link: 58
      left_qbhand_middle_middle_virtual_link: 59
      left_qbhand_middle_middle_link: 60
      left_qbhand_middle_distal_virtual_link: 61
      left_qbhand_middle_distal_link: 62
      left_qbhand_ring_knuckle_link: 63
      left_qbhand_ring_proximal_virtual_link: 64
      left_qbhand_ring_proximal_link: 65
      left_qbhand_ring_middle_virtual_link: 66
      left_qbhand_ring_middle_link: 67
      left_qbhand_ring_distal_virtual_link: 68
      left_qbhand_ring_distal_link: 69
      left_qbhand_little_knuckle_link: 70
      left_qbhand_little_proximal_virtual_link: 71
      left_qbhand_little_proximal_link: 72
      left_qbhand_little_middle_virtual_link: 73
      left_qbhand_little_middle_link: 74
      left_qbhand_little_distal_virtual_link: 75  
      left_qbhand_little_distal_link: 76
      right_thigh: 77
      right_shin: 78
      right_foot: 79
      left_thigh: 80
      left_shin: 81
      left_foot: 82
    dofs:
      abdomen_x: 0
      abdomen_y: 1
      abdomen_z: 2
      neck_x: 3
      neck_y: 4
      neck_z: 5
      right_shoulder_x: 6
      right_shoulder_y: 7
      right_shoulder_z: 8
      right_elbow: 9
      right_hand_x: 10
      right_hand_y: 11
      right_hand_z: 12
      right_qbhand_thumb_knuckle_joint: 13
      right_qbhand_thumb_proximal_joint: 14
      right_qbhand_thumb_proximal_virtual_joint: 15
      right_qbhand_thumb_distal_joint: 16
      right_qbhand_thumb_distal_virtual_joint: 17
      right_qbhand_index_knuckle_joint: 18
      right_qbhand_index_proximal_joint: 19
      right_qbhand_index_proximal_virtual_joint: 20
      right_qbhand_index_middle_joint: 21
      right_qbhand_index_middle_virtual_joint: 22
      right_qbhand_index_distal_joint: 23
      right_qbhand_index_distal_virtual_joint: 24
      right_qbhand_middle_knuckle_joint: 25
      right_qbhand_middle_proximal_joint: 26
      right_qbhand_middle_proximal_virtual_joint: 27
      right_qbhand_middle_middle_joint: 28
      right_qbhand_middle_middle_virtual_joint: 29
      right_qbhand_middle_distal_joint: 30
      right_qbhand_middle_distal_virtual_joint: 31
      right_qbhand_ring_knuckle_joint: 32
      right_qbhand_ring_proximal_joint: 33
      right_qbhand_ring_proximal_virtual_joint: 34
      right_qbhand_ring_middle_joint: 35
      right_qbhand_ring_middle_virtual_joint: 36
      right_qbhand_ring_distal_joint: 37
      right_qbhand_ring_distal_virtual_joint: 38
      right_qbhand_little_knuckle_joint: 39
      right_qbhand_little_proximal_joint: 40
      right_qbhand_little_proximal_virtual_joint: 41
      right_qbhand_little_middle_joint: 42
      right_qbhand_little_middle_virtual_joint: 43
      right_qbhand_little_distal_joint: 44
      right_qbhand_little_distal_virtual_joint: 45
      left_shoulder_x: 46
      left_shoulder_y: 47
      left_shoulder_z: 48
      left_elbow: 49
      left_hand_x: 50
      left_hand_y: 51
      left_hand_z: 52
      left_qbhand_thumb_knuckle_joint: 53
      left_qbhand_thumb_proximal_joint: 54
      left_qbhand_thumb_proximal_virtual_joint: 55
      left_qbhand_thumb_distal_joint: 56
      left_qbhand_thumb_distal_virtual_joint: 57
      left_qbhand_index_knuckle_joint: 58
      left_qbhand_index_proximal_joint: 59
      left_qbhand_index_proximal_virtual_joint: 60
      left_qbhand_index_middle_joint: 61
      left_qbhand_index_middle_virtual_joint: 62
      left_qbhand_index_distal_joint: 63
      left_qbhand_index_distal_virtual_joint: 64
      left_qbhand_middle_knuckle_joint: 65
      left_qbhand_middle_proximal_joint: 66
      left_qbhand_middle_proximal_virtual_joint: 67
      left_qbhand_middle_middle_joint: 68
      left_qbhand_middle_middle_virtual_joint: 69
      left_qbhand_middle_distal_joint: 70
      left_qbhand_middle_distal_virtual_joint: 71
      left_qbhand_ring_knuckle_joint: 72
      left_qbhand_ring_proximal_joint: 73
      left_qbhand_ring_proximal_virtual_joint: 74
      left_qbhand_ring_middle_joint: 75
      left_qbhand_ring_middle_virtual_joint: 76
      left_qbhand_ring_distal_joint: 77
      left_qbhand_ring_distal_virtual_joint: 78
      left_qbhand_little_knuckle_joint: 79
      left_qbhand_little_proximal_joint: 80
      left_qbhand_little_proximal_virtual_joint: 81
      left_qbhand_little_middle_joint: 82
      left_qbhand_little_middle_virtual_joint: 83
      left_qbhand_little_distal_joint: 84
      left_qbhand_little_distal_virtual_joint: 85
      right_hip_x: 86
      right_hip_y: 87
      right_hip_z: 88
      right_knee: 89
      right_ankle_x: 90
      right_ankle_y: 91
      right_ankle_z: 92
      left_hip_x: 93
      left_hip_y: 94
      left_hip_z: 95
      left_knee: 96
      left_ankle_x: 97
      left_ankle_y: 98
      left_ankle_z: 99
    dof_offsets: [0, 3, 6, 9, 10, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 49, 50, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 89, 90, 93, 96, 97, 100]




  
