name: CURI

physics_engine: 'physx'  #  'physx' or 'flex'
graphics_device_id: 0
sim_device: 'cuda:0'

env:
  numEnvs: 1
  envSpacing: 3.

  asset:
    assetFile:
    assetRoot:
    init_pose: [0.0, 0.0, 1.1, 0.0, 0.0, 0.0, 1.0]
    armature: 0.01   # The value added to the diagonal elements of inertia tensors for all of the asset’s rigid bodies/links. Could improve simulation stability
    collapse_fixed_joints: # Merge links that are connected by fixed joints.
    convex_decomposition_from_submeshes: False  # Whether to treat submeshes in the mesh as the convex decomposition of the mesh. Default False.
    disable_gravity: False  # Whether to disable gravity for the asset. Default False.
    fix_base_link: False  # Set Asset base to a fixed placement upon import.
    flip_visual_attachments: False  # Switch Meshes from Z-up left-handed system to Y-up Right-handed coordinate system.
    use_mesh_materials: True  # Whether to use mesh materials. Default False.
    vhacd_enabled: True  # Whether convex decomposition is enabled. Used only with PhysX. Provided by a third part library (V-HACD). Default False.
    vhacd_params:  # Convex decomposition parameters. Used only with PhysX. If not specified, all triangle meshes will be approximated using a single convex hull.
      resolution: 100000  # Maximum number of voxels generated during the voxelization stage. Default 100000.
      max_convex_hulls: 10  # Maximum number of convex hulls to generate. Default 10.
      max_num_vertices_per_ch: 64  # Maximum number of vertices per convex hull. Default 64.


sim:
  dt: 0.0166 # 1/60
  substeps: 1
  up_axis: "Z"
  use_gpu_pipeline: False
  gravity: ${if:${eq:${.up_axis}, "Y"}, [0, -9.81, 0], [0, 0, -9.81]}
  physx:
    num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
    solver_type: 1 # 0: pgs, 1: tgs
    use_gpu: False # set to False to run on CPU
    num_position_iterations: 12
    num_velocity_iterations: 1
    contact_offset: 0.005
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 1000.0
    num_subscenes: 4 # Splits the simulation into N physics scenes and runs each one in a separate thread
    contact_collection: 0 # 0: CC_NEVER (don't collect contact info), 1: CC_LAST_SUBSTEP (collect only contacts on last substep), 2: CC_ALL_SUBSTEPS (default - all contacts)
    friction_offset_threshold: 0.001
    friction_correlation_distance: 0.0005

