total_timesteps: 1000000
ppo:
  n_steps: 128
  gamma: 0.99
  ent_coef: 0.01
  learning_rate: 2.5e-4
  vf_coef: 0.5
  max_grad_norm: 0.5
  gae_lambda: 0.95
  batch_size: 32
  n_epochs: 10
  clip_range: 0.2