# Relevant to rofunc/simulator/assets
description_file_path: "urdf/curi/urdf/curi_isaacgym_dual_arm.urdf"

initial_base_pose: [0.0, 0.0, 0.0, -0.707107, 0.0, 0.0, 0.707107]

fix_base_link: True

flip_visual_attachments: True

