# Relevant to rofunc/simulator/assets
description_file_path: "urdf/human/human_xsenstemplate_48dof.urdf"

initial_base_pose: [0.0, 2.0, 0.0, -0.707107, 0.0, 0.0, 0.707107]

fix_base_link: False

flip_visual_attachments: False
