# Relevant to rofunc/simulator/assets
description_file_path: "urdf/walker/urdf/walker_cartesio.urdf"

initial_base_pose: [0.0, 1.3, 0.0, -0.707107, 0.0, 0.0, 0.707107]

fix_base_link: True

flip_visual_attachments: False
