keyBodies: [ "HAND_R", "HAND_L", "FOOT_R", "FOOT_L" ]
contactBodies: [ "FOOT_R", "FOOT_L" ]


# animation files to learn from
motion_file: "examples/data/hotu2/20240509/all_zju_motion.yaml"

use_extra_dof_states_motion: True
extra_rewrite_dof_names: "all"

motion_file_asset: "mjcf/zju_humanoid/zju_humanoid_w_qbhand.xml"

object_motion_file:

asset:
  assetFileName: "mjcf/zju_humanoid/zju_humanoid_w_qbhand.xml"

use_object_motion: False
object_asset:
  assetName:    # List of object names, also used for finding objects in object_motion_file, if the name is box or sphere, it will be created as a box or sphere
  assetFileName:     # List of object asset file path
  assetSize:         # List of object size, used for scaling the object and creating the box objects
