class_name: HumanoidViewMotion
asset_name: "mjcf/amp_humanoid_spoon_pan.xml"
asset_body_num: 19
asset_joint_num: 44

keyBodies: ["right_hand", "left_hand", "right_foot", "left_foot"]
contactBodies: ["right_foot", "left_foot"]
