wandb_version: 1

task:
  desc: null
  value:
    name: Humanoid
    physics_engine: physx
    env:
      numEnvs: 4096
      envSpacing: 5
      episodeLength: 1000
      enableDebugVis: false
      clipActions: 1.0
      powerScale: 1.0
      headingWeight: 0.5
      upWeight: 0.1
      actionsCost: 0.01
      energyCost: 0.05
      dofVelocityScale: 0.1
      angularVelocityScale: 0.25
      contactForceScale: 0.01
      jointsAtLimitCost: 0.25
      deathCost: -1.0
      terminationHeight: 0.8
      asset:
        assetFileName: mjcf/nv_humanoid.xml
      plane:
        staticFriction: 1.0
        dynamicFriction: 1.0
        restitution: 0.0
      enableCameraSensors: false
    sim:
      dt: 0.0166
      substeps: 2
      up_axis: z
      use_gpu_pipeline: true
      gravity:
      - 0.0
      - 0.0
      - -9.81
      physx:
        num_threads: 4
        solver_type: 1
        use_gpu: false
        num_position_iterations: 4
        num_velocity_iterations: 0
        contact_offset: 0.02
        rest_offset: 0.0
        bounce_threshold_velocity: 0.2
        max_depenetration_velocity: 10.0
        default_buffer_size_multiplier: 5.0
        max_gpu_contact_pairs: 8388608
        num_subscenes: 4
        contact_collection: 0
    task:
      randomize: false
      randomization_params:
        frequency: 600
        observations:
          range:
          - 0
          - 0.002
          operation: additive
          distribution: gaussian
        actions:
          range:
          - 0.0
          - 0.02
          operation: additive
          distribution: gaussian
        sim_params:
          gravity:
            range:
            - 0
            - 0.4
            operation: additive
            distribution: gaussian
            schedule: linear
            schedule_steps: 3000
        actor_params:
          humanoid:
            color: true
            rigid_body_properties:
              mass:
                range:
                - 0.5
                - 1.5
                operation: scaling
                distribution: uniform
                setup_only: true
                schedule: linear
                schedule_steps: 3000
            rigid_shape_properties:
              friction:
                num_buckets: 500
                range:
                - 0.7
                - 1.3
                operation: scaling
                distribution: uniform
                schedule: linear
                schedule_steps: 3000
              restitution:
                range:
                - 0.0
                - 0.7
                operation: scaling
                distribution: uniform
                schedule: linear
                schedule_steps: 3000
            dof_properties:
              damping:
                range:
                - 0.5
                - 1.5
                operation: scaling
                distribution: uniform
                schedule: linear
                schedule_steps: 3000
              stiffness:
                range:
                - 0.5
                - 1.5
                operation: scaling
                distribution: uniform
                schedule: linear
                schedule_steps: 3000
              lower:
                range:
                - 0
                - 0.01
                operation: additive
                distribution: gaussian
                schedule: linear
                schedule_steps: 3000
              upper:
                range:
                - 0
                - 0.01
                operation: additive
                distribution: gaussian
                schedule: linear
                schedule_steps: 3000
train:
  desc: null
  value:
    Trainer:
      experiment_name: null
      experiment_directory: null
      write_interval: 100
      checkpoint_interval: null
      wandb: true
      wandb_kwargs:
        project: RofuncRL
        name: null
      rofunc_logger_kwargs:
        verbose: true
      maximum_steps: 100000
      random_steps: 0
      start_learning_steps: 0
      seed: 42
      rollouts: 16
      max_episode_steps: 200
      eval_flag: false
      eval_freq: 1000
      eval_steps: 1000
      use_eval_thread: false
      inference_steps: 1000
    Agent:
      discount: 0.99
      td_lambda: 0.95
      learning_epochs: 8
      mini_batch_size: 8
      lr_a: 0.0005
      lr_c: 0.0005
      adam_eps: 1.0e-05
      use_gae: true
      entropy_loss_scale: 0.01
      value_loss_scale: 2.0
      grad_norm_clip: 1.0
      ratio_clip: 0.2
      value_clip: 0.2
      clip_predicted_values: true
      kl_threshold: 0
    Model:
      use_init: true
      use_action_clip: true
      use_same_model: false
      use_action_out_tanh: true
      action_clip: 1.0
      action_scale: 1.0
      use_log_std_clip: true
      log_std_clip_max: 2.0
      log_std_clip_min: -20
      actor:
        type: Gaussian
        mlp_hidden_dims:
        - 512
        - 256
        - 128
        mlp_activation: elu
        use_lstm: false
        lstm_cell_size: 256
        lstm_use_prev_action: false
        lstm_use_prev_reward: false
        max_seq_len: 20
      critic:
        mlp_hidden_dims:
        - 512
        - 256
        - 128
        mlp_activation: elu
        use_lstm: false
        lstm_cell_size: 256
        lstm_use_prev_action: false
        lstm_use_prev_reward: false
        max_seq_len: 20
task_name:
  desc: null
  value: Humanoid
experiment:
  desc: null
  value: ''
num_envs:
  desc: null
  value: 4096
seed:
  desc: null
  value: 42
torch_deterministic:
  desc: null
  value: false
max_iterations:
  desc: null
  value: ''
physics_engine:
  desc: null
  value: physx
pipeline:
  desc: null
  value: gpu
sim_device:
  desc: null
  value: gpu
device_id:
  desc: null
  value: 0
rl_device:
  desc: null
  value: cuda:1
multi_gpu:
  desc: null
  value: false
num_threads:
  desc: null
  value: 4
solver_type:
  desc: null
  value: 1
num_subscenes:
  desc: null
  value: 4
inference:
  desc: null
  value: false
checkpoint:
  desc: null
  value: ''
headless:
  desc: null
  value: true
enable_livestream:
  desc: null
  value: false
mt_timeout:
  desc: null
  value: 30
capture_video:
  desc: null
  value: false
capture_video_freq:
  desc: null
  value: 1464
capture_video_len:
  desc: null
  value: 100
force_render:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.30.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705149440.201518
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 76
      3:
      - 13
      - 16
      - 23
      - 34
      4: 3.8.18
      5: 0.16.2
      6: 4.30.1
      8:
      - 5
      13: linux-x86_64
