nbData: 100                             # Number of datapoints
nbIter: 100                             # Maximum number of iterations for iLQR
nbVarPos: 3                             # Dimension of position data (here: x1,x2)
nbDeriv: 2                              # Number of static and dynamic features (nbDeriv=2 for [x,dx] and u=ddx)
nbPoints: 4                             # Number of via-points to track
nbVarX: 6                               # State space dimension (x1,x2,x3)
nbVarU: 6                               # Control space dimension (dx1,dx2,dx3)
nbVarF: 6                               # Objective function dimension (f1,f2,f3, with f3 as orientation)
dt: 0.2                                # Time step duration
rfactor: 1E-6                           # control cost in LQR

# For robot
sz: [ .2, .3, .2, .2, .2, .2 ]                          # Size of objects
useBoundingBox: False                    # Consider bounding boxes for reaching cost
basisName: "PIECEWISE"                        # can be PIECEWISE, RBF, BERNSTEIN, FOURIER
nbFct: 5                                # Number of basis function
