nbData: 1000                             # Number of datapoints
nbVarU: 7                               # Control space dimension (dx1,dx2,dx3)
nbVarPos: 7                             # Control space dimension (dx1,dx2,dx3)
nbDeriv: 2                              # Number of static and dynamic features (nbDeriv=2 for [x,dx] and u=ddx)
nbVar: ${multi:${nbVarPos},${nbDeriv}}  # Dimension of state vector
nbVarX: ${add:${nbVar}, 1}              # Augmented state space
dt: 1E-2                                # Time step duration
rfactor: 5E-8                           # control cost in LQR
nbFct: 20                                # Number of basis function
basisName: "RBF"                    # can be PIECEWEISE, RBF, BERNSTEIN, FOURIER
nbPoints: 0                             # Number of via-points to track
